# Generated by Django 4.1.7 on 2024-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('year_obtained', models.CharField(max_length=4)),
                ('cert_expiry_date', models.DateTimeField(max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
