# Generated by Django 4.1.7 on 2024-01-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
    ]
