# Generated by Django 4.1.7 on 2024-01-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie"),
        ("certifications", "0003_alter_certification_cert_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="movie",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
            ),
            preserve_default=False,
        ),
    ]
