# Generated by Django 4.1.7 on 2024-01-31 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certifications", "0004_certification_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="movie",
        ),
    ]
